#!/usr/bin/env bash
set -euo pipefail

# Production deploy wrapper.
# Override via environment variables if needed.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_ENV_FILE="${DEPLOY_ENV_FILE:-$SCRIPT_DIR/deploy.env}"

if [[ -f "$DEPLOY_ENV_FILE" ]]; then
	# shellcheck disable=SC1090
	source "$DEPLOY_ENV_FILE"
fi

DEPLOY_HOST="${DEPLOY_HOST:-${PRODUCTION_HOST:-}}"
DEPLOY_SSH_USER="${DEPLOY_SSH_USER:-${PRODUCTION_SSH_USER:-}}"
DEPLOY_SSH_PORT="${DEPLOY_SSH_PORT:-${PRODUCTION_SSH_PORT:-22}}"
DEPLOY_REPO_DIR="${DEPLOY_REPO_DIR:-${PRODUCTION_REPO_DIR:-/var/www/www.roboktober.nl}}"
DEPLOY_BRANCH="${DEPLOY_BRANCH:-${PRODUCTION_BRANCH:-master}}"
DEPLOY_RUN_MIGRATIONS="${DEPLOY_RUN_MIGRATIONS:-${PRODUCTION_RUN_MIGRATIONS:-true}}"
DEPLOY_BUILD_FRONTEND="${DEPLOY_BUILD_FRONTEND:-${PRODUCTION_BUILD_FRONTEND:-false}}"
DEPLOY_PHP_BIN="${DEPLOY_PHP_BIN:-${PRODUCTION_PHP_BIN:-}}"
DEPLOY_COMPOSER_BIN="${DEPLOY_COMPOSER_BIN:-${PRODUCTION_COMPOSER_BIN:-}}"
DEPLOY_DRY_RUN="${DEPLOY_DRY_RUN:-false}"

export DEPLOY_HOST
export DEPLOY_SSH_USER
export DEPLOY_SSH_PORT
export DEPLOY_REPO_DIR
export DEPLOY_BRANCH
export DEPLOY_RUN_MIGRATIONS
export DEPLOY_BUILD_FRONTEND
export DEPLOY_PHP_BIN
export DEPLOY_COMPOSER_BIN
export DEPLOY_DRY_RUN

"$SCRIPT_DIR/deploy-remote.sh"
